### ISSUE TITLE
An exception raised when obtaining container image metadata

### ISSUE THREAD

**Issue by fridex** [thoth-station/common#1108]
**Describe the bug**

```
Internal error in sentry_sdk
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/sentry_sdk/client.py", line 211, in _prepare_event
    new_event = before_send(event, hint or {})
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/logging.py", line 201, in before_send_handler
    if exp_signature == log_record["name"]:
TypeError: string indices must be integers
```

**To Reproduce**
1. Go to test environment
2. Ask for container image metadata
3. See internal error on User API reported
4. See the error posted in User API logs

**Expected behavior**

Container image metadata should be available to users

**Comment by fridex** [comment]
Actually the error was in the wrong image name which had curly braces `{}`. This caused string expansion on user API and caused this error. Closing. Sorry for the confusion.
