### ISSUE TITLE
Logging level cannot be set for mi-scheduler

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/common#1140]
**Describe the bug**
When trying to set envvar `THOTH_LOG_MI_SCHEDULER` within `mi-scheduler`'s cronjob (see https://github.com/thoth-station/thoth-application/blob/01c358b9fa29b2d7eb330493165f71ce85563371/mi-scheduler/base/cronjob.yaml#L152), there's an error somewhere, see the job's log:
```
[xtuchyna@c01-424a ~]$ oc logs mi-kebechet-vfv4t 
Traceback (most recent call last):
  File "app.py", line 33, in <module>
    init_logging()
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/logging.py", line 281, in init_logging
    _init_log_levels(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/logging.py", line 83, in _init_log_levels
    level = getattr(logging, level)
AttributeError: module 'logging' has no attribute '${THOTH_LOG_MI_SCHEDULER}'
```

**To Reproduce**
1. Go to `thoth-test-core` namespace on `ocp4`
2. Create a new job out of mi-scheduler cronjob (and possibly delete the old one)

- delete: `oc delete job mi-kebechet `
- create a new one: `oc create job --from=cronjob/mi-scheduler-kebechet mi-kebechet`

3. Output the job's log `oc logs mi-kebechet-<id>`

**Comment by xtuchyna** [comment]
yes, sorry for not closing the issue - kind of forgot about it
