### ISSUE TITLE
When scheduling mi workflow, ` Unprocessable Entity` error comes up

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/common#1174]
**Describe the bug**
When scheduling workflow out of `mi-kebechet-merge` , the `Unprocessable Entity` error raises up.
 
**To Reproduce**
1. `oc project thoth-test-core` (zero cluster)
2. `oc create job --from=cronjob/mi-scheduler-kebechet-merge mi-keb-merge-test`
3. `oc logs -f mi-keb-merge-test...`

**LOG**
```
Traceback (most recent call last):
  File "app.py", line 167, in <module>
    main(auto_envvar_prefix="SCHEDULE")
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "app.py", line 162, in main
    Schedule(openshift=oc).schedule_for_kebechet_merge()
  File "app.py", line 119, in schedule_for_kebechet_merge
    workflow_id = self.oc.schedule_mi_workflow(knowledge_path=path, mi_used_for_thoth=True, mi_merge=True)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/openshift.py", line 1536, in schedule_mi_workflow
    return self._schedule_workflow(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/openshift.py", line 1083, in _schedule_workflow
    return workflow(**parameters)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/workflows.py", line 854, in submit_mi
    workflow_id: Optional[str] = self.submit_workflow_from_template(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/workflows.py", line 497, in submit_workflow_from_template
    template = self.get_workflow_template(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/workflows.py", line 196, in get_workflow_template
    template = self.openshift.oc_process(namespace, template)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/common/openshift.py", line 1730, in oc_process
    response.raise_for_status()
  File "/opt/app-root/lib64/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://172.30.0.1:443/apis/template.openshift.io/v1/namespaces/thoth-test-core/processedtemplates

```

**Comment by xtuchyna** [comment]
This was due to the absence of `MI_MERGE` parameter in templates. Closing the issue
