### ISSUE TITLE
Add support for openshift-restclient 0.8+

### ISSUE THREAD

**Issue by fridex** [thoth-station/common#342]
When switching to a newer version, we need to adjust api version to openshift specific resources, for templates it is `template.openshift.io/v1`. The same applies for imagestreams, builds used on Amun.

```
>>> from thoth.common import OpenShift
>>> os = OpenShift()
Failed to load in cluster configuration, fallback to a local development setup: Service host/port is not set.
/home/fpokorny/.local/share/virtualenvs/common-VmnF3EMa/lib/python3.6/site-packages/kubernetes/config/kube_config.py:496: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict=yaml.load(f),
TLS verification when communicating with k8s/okd master is disabled
>>> os.get_adviser_template()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fpokorny/github.com/thoth-station/common/thoth/common/openshift.py", line 1189, in get_adviser_template
    response = self.ocp_client.resources.get(api_version="template.openshift.io/v1", kind="Template").get(
AttributeError: 'list' object has no attribute 'get'
```

Also newer openshift-rest-client returns a list of templates:
```
[<Resource(template.openshift.io/v1/processedtemplates)>, <Resource(template.openshift.io/v1/templates)>]
```

**Comment by fridex** [comment]
A simple test: log in to cluster and you can use thoth-common from within your command line (inside the `common` repo):

```
PYTHONPATH=. THOTH_INFRA_NAMESPACE=thoth-test-core KUBERNETES_VERIFY_TLS=0 pipenv run python3

>>> from thoth.common import OpenShift
>>> os = OpenShift()
Failed to load in cluster configuration, fallback to a local development setup: Service host/port is not set.
/home/fpokorny/.local/share/virtualenvs/common-VmnF3EMa/lib/python3.6/site-packages/kubernetes/config/kube_config.py:460: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict=yaml.load(f),
TLS verification when communicating with k8s/okd master is disabled
>>> os.get_adviser_template()
```

**Comment by goern** [comment]
@CermakM @fridex how does this issue relate to https://github.com/thoth-station/common/commit/6cf6af111b8a880e01b92920d14847b84ed2bb5a ?

**Comment by CermakM** [comment]
At least part of the issue described here should have been fixed by https://github.com/thoth-station/common/commit/fb457270d1aa0190e7e5b8367d738f7654352a8f

**Comment by goern** [comment]
what is the status of this?

**Comment by CermakM** [comment]
I haven't observed any issues while using `~0.10.0`
