### ISSUE TITLE
Error if OpenShift and Kubernetes clients are not pinned down

### ISSUE THREAD

**Issue by fridex** [thoth-station/common#67]
This is an error found when starting user-api with openshift enabled:

```console

[2018-08-29 09:32:50 +0000] [27] [ERROR] Exception in worker process
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
  | __import__(module)
  | File "/opt/app-root/src/thoth_user_api/entrypoint.py", line 41, in <module>
  | app.add_api(Configuration.SWAGGER_YAML_PATH)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 54, in add_api
  | api = super(FlaskApp, self).add_api(specification, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apps/abstract.py", line 162, in add_api
  | options=api_options.as_dict())
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/abstract.py", line 146, in __init__
  | self.add_paths()
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/abstract.py", line 272, in add_paths
  | self._handle_add_operation_error(path, method, sys.exc_info())
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/abstract.py", line 283, in _handle_add_operation_error
  | six.reraise(*exc_info)
  | File "/opt/app-root/lib/python3.6/site-packages/six.py", line 686, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/abstract.py", line 262, in add_paths
  | self.add_operation(method, path, endpoint, path_parameters)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/abstract.py", line 215, in add_operation
  | pass_context_arg_name=self.pass_context_arg_name)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/operation.py", line 228, in __init__
  | resolution = resolver.resolve(self)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
  | return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
  | return self.function_resolver(operation_id)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/utils.py", line 36, in get_function_from_name
  | module = importlib.import_module(module_name)
  | File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | File "/opt/app-root/src/thoth_user_api/api_v1.py", line 39, in <module>
  | _OPENSHIFT = OpenShift()
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 51, in __init__
  | self.ocp_client = DynamicClient(client.ApiClient(configuration=client.Configuration()))
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 58, in __init__
  | self._load_server_info()
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 62, in _load_server_info
  | self.__version = {'kubernetes': load_json(self.request('get', '/version'))}
  | File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 255, in request
  | _return_http_data_only=params.get('_return_http_data_only', True)
  | TypeError: call_api() got an unexpected keyword argument 'async'
```

**Comment by fridex** [comment]
Already fix in the current master - https://github.com/thoth-station/common/blob/master/setup.py#L53-L54
