### ISSUE TITLE
Advise cannot be scheduled in new cluster

### ISSUE THREAD

**Issue by pacospace** [thoth-station/common#882]
**Describe the bug**
thoth-application is the source of truth for what is deployed in the new cluster. We migrated template from components to thoth-application removing labels-selector. This cause an issue with current implementation because we schedule jobs and workflows looking for label_selector=`template=<component>`. Therefore in the new cluster the implementation does not work.

**To Reproduce**
1. Schedule one thamos advise using new cluster.

**Expected behavior**
Adviser workflows start.

**Screenshots**
```
2020-06-24 20:50:09,981  26 ERROR    thoth.user_api.openapi_server:1892: Exception on /api/v1/advise/python [POST]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 327, in post_advise_python
    response, status = _do_schedule(parameters, _OPENSHIFT.schedule_adviser, output=Configuration.THOTH_ADVISER_OUTPUT)
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 864, in _do_schedule
    return {"analysis_id": runner(**parameters, **runner_kwargs), "parameters": parameters, "cached": False}, 202
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1715, in schedule_adviser
    "workflow_parameters": workflow_parameters,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1215, in _schedule_workflow
    return workflow(**parameters)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 552, in submit_adviser_workflow
    workflow_namespace=self.openshift.backend_namespace,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 485, in submit_workflow_from_template
    namespace, label_selector, parameters=template_parameters
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 188, in get_workflow_template
    template = self.openshift._get_template(label_selector, namespace=namespace)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 700, in _get_template
    self._raise_on_invalid_response_size(response)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 2451, in _raise_on_invalid_response_size
    f"Application misconfiguration - number of templates available in the infra namespace "
RuntimeError: Application misconfiguration - number of templates available in the infra namespace 'thoth-test-core' is 0, should be 1.
```

**Additional context**
New cluster labels are created by Argo directly.

**Comment by goern** [comment]
@saisankargochhayat could you test it again?

**Comment by saisankargochhayat** [comment]
> @saisankargochhayat could you test it again?

That error seem's to be resolved. Now it only shows these warnings - 
```
2020-06-25 15:30:29,110  26 WARNING  thoth.common.config.runtime_environment:77: Unknown configuration entry in the configuration file 'ipython' with value {}
2020-06-25 15:30:29,174  26 WARNING  thoth.common.openshift:315: Requested to assign parameter 'IMAGE_STREAM_NAMESPACE' (value 'thoth-test-core') to template but template does not provide the given parameter, forcing...
```
